services:
  - type: web
    name: task-manager-backend
    env: node
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: task-manager-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: "24h"
      - key: CORS_ORIGIN
        value: "https://your-frontend-url.onrender.com"

databases:
  - name: task-manager-db
    databaseName: taskmanager
    user: taskmanager
